### ISSUE TITLE
Can't resolve recent commit

### ISSUE THREAD

**Issue by lexxvir** [jethrogb/rustc-commit-db#2]
Hi @jethrogb,

Thank you for [core_io](https://github.com/jethrogb/rust-core_io) crate!

I'd like to update it to recent nightly, but it seems `rustc-commit-db` can't found one of recent commits, [3c9e884dd3bf93b1516d3b5858072b7659c4cfba](https://github.com/rust-lang/rust/commit/3c9e884dd3bf93b1516d3b5858072b7659c4cfba):

```
± ./commit-db.rb lookup 3c9e884dd3bf93b1516d3b5858072b7659c4cfba
./commit-db.rb:141:in `resolve_commit': GitHub returned error: 3c9e884dd3bf93b1516d3b5858072b7659c4cfba (RuntimeError)
	from ./commit-db.rb:156:in `lookup'
	from ./commit-db.rb:250:in `lookup_by_commit'
	from ./commit-db.rb:294:in `block in <main>'
	from ./commit-db.rb:291:in `each'
	from ./commit-db.rb:291:in `<main>'
```

It is commit that was HEAD when I cloned rust git repo some times ago.
So I'd like to find all commits between that commit and that used for 2018-03-07 (last published version of `core_io`).

That outputs by `update` command:

```
 ± ./commit-db.rb update
Checking for release updates on beta
Retrieved 64 new releases
Latest dist nightly: 
```

Thanks,

**Comment by jethrogb** [comment]
Sorry for the hilariously late response.

1. There was a bug, you'd have to run `./commit-db.rb update --force` for it to work at all. This is fixed now.

2. `./commit-db.rb lookup` can only tell you about commits that were used in an actual Rust release (nightly/beta/stable). It won't be able to tell you about other commits that may exist in-between. If you want to add that functionality, I'd be glad to accept your PR.

**Comment by lexxvir** [comment]
Thank you for answer & update!

1. Just in case, `./commit-db.rb update --force` reports error for me:
```
± ./commit-db.rb update --force                               
Checking for release updates on beta
/var/lib/gems/2.3.0/gems/aws-sigv4-1.0.3/lib/aws-sigv4/signer.rb:517:in `extract_credentials_provider': missing credentials, provide credentials with one of the following options: (Aws::Sigv4::Errors::MissingCredentialsError)
  - :access_key_id and :secret_access_key
  - :credentials
  - :credentials_provider
	from /var/lib/gems/2.3.0/gems/aws-sigv4-1.0.3/lib/aws-sigv4/signer.rb:121:in `initialize'
	from /var/lib/gems/2.3.0/gems/aws-sdk-s3-1.30.0/lib/aws-sdk-s3/plugins/s3_signer.rb:189:in `new'
	from /var/lib/gems/2.3.0/gems/aws-sdk-s3-1.30.0/lib/aws-sdk-s3/plugins/s3_signer.rb:189:in `build_v4_signer'
	from /var/lib/gems/2.3.0/gems/aws-sdk-s3-1.30.0/lib/aws-sdk-s3/plugins/s3_signer.rb:13:in `block in <class:S3Signer>'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:70:in `call'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:211:in `block in resolve_defaults'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:57:in `each'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:57:in `each'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:210:in `resolve_defaults'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:203:in `value_at'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:189:in `block in resolve'
	from /usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
	from /usr/lib/ruby/2.3.0/set.rb:306:in `each'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:189:in `resolve'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/configuration.rb:150:in `build!'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/base.rb:62:in `build_config'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/base.rb:19:in `initialize'
	from /var/lib/gems/2.3.0/gems/aws-sdk-s3-1.30.0/lib/aws-sdk-s3/client.rb:262:in `initialize'
	from /var/lib/gems/2.3.0/gems/aws-sdk-core-3.44.1/lib/seahorse/client/base.rb:99:in `new'
	from ./commit-db.rb:217:in `update'
	from ./commit-db.rb:299:in `block in <main>'
	from ./commit-db.rb:297:in `each'
	from ./commit-db.rb:297:in `<main>'
```

2. I'd like use any version after 1.31.0 (2018 edition), no certain commit required. Now, when you updated DB, I can choose it.

**Comment by jethrogb** [comment]
Cool. I've filed issue #3 for the AWS credentials problem.
